- hosts: server
  become: yes
  vars:
    prometheus_version: "2.52.0"
    grafana_version: "10.0.0"
    postgres_exporter_target: "localhost:9187"

  tasks:

    #########################################
    # Installer Prometheus
    #########################################
    - name: Installer Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Démarrer et activer Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Ajouter Postgres Exporter au scrape_configs Prometheus
      blockinfile:
        path: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK postgres"
        insertafter: "scrape_configs:"  # <-- Assure que c'est dans scrape_configs
        block: |
          - job_name: 'postgres'
            static_configs:
              - targets: ['{{ postgres_exporter_target }}']
      notify: Restart Prometheus

    #########################################
    # Installer Grafana
    #########################################
    - name: Installer les prérequis pour Grafana
      apt:
        name:
          - software-properties-common
          - wget
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Ajouter le dépôt officiel Grafana
      apt_repository:
        repo: "deb [arch=amd64] https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Installer Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Démarrer et activer Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted

